// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC31BnpbPA3oC65E7OKstQiPG2HXDAvLzk',
    appId: '1:1023555473955:web:fe2477878b6ec58c611796',
    messagingSenderId: '1023555473955',
    projectId: 'cliniq-10039',
    authDomain: 'cliniq-10039.firebaseapp.com',
    storageBucket: 'cliniq-10039.firebasestorage.app',
    measurementId: 'G-HLV79L6BMP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzyfDJwWXtzMXpZ5yNjkxvgg7Ogc19kR4',
    appId: '1:1023555473955:android:4cd57a4e8bdb0472611796',
    messagingSenderId: '1023555473955',
    projectId: 'cliniq-10039',
    storageBucket: 'cliniq-10039.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4kTni6gn6Q4OGzpQplvrDoa97qA1dvZo',
    appId: '1:1023555473955:ios:ad926dc5ee13441d611796',
    messagingSenderId: '1023555473955',
    projectId: 'cliniq-10039',
    storageBucket: 'cliniq-10039.firebasestorage.app',
    iosClientId: '1023555473955-qh97o2hde9ejvirjf92sl6vlmt78dpit.apps.googleusercontent.com',
    iosBundleId: 'com.example.cliniq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4kTni6gn6Q4OGzpQplvrDoa97qA1dvZo',
    appId: '1:1023555473955:ios:ad926dc5ee13441d611796',
    messagingSenderId: '1023555473955',
    projectId: 'cliniq-10039',
    storageBucket: 'cliniq-10039.firebasestorage.app',
    iosClientId: '1023555473955-qh97o2hde9ejvirjf92sl6vlmt78dpit.apps.googleusercontent.com',
    iosBundleId: 'com.example.cliniq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC31BnpbPA3oC65E7OKstQiPG2HXDAvLzk',
    appId: '1:1023555473955:web:95a79b960e1b7f16611796',
    messagingSenderId: '1023555473955',
    projectId: 'cliniq-10039',
    authDomain: 'cliniq-10039.firebaseapp.com',
    storageBucket: 'cliniq-10039.firebasestorage.app',
    measurementId: 'G-G57FTP5TTV',
  );

}